apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-tolerations
  namespace: minhtao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mods-3
  template:
    metadata:
      labels:
        app: mods-3
      annotations:  # Thêm phần annotations nếu cần
        workload: "production-1"
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "db"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - devopsteam-minhkq-k8s-mods-3
      containers:
      - name: mods-3
        image: nginx:latest
        ports:
        - containerPort: 80
