apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods1-deployment
  namespace: taint2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mods-taints
  template:
    metadata:
      labels:
        app: mods-taints
    spec:
      tolerations:  # Đây là nơi để đưa tolerations
        - key: "app"         # Key của taint mà toleration áp dụng
          operator: "Equal"   # Phép toán so sánh (Equal, Exists, ...)
          value: "db"   # Giá trị của taint
          effect: "NoSchedule"  # Tác động của taint (NoSchedule, PreferNoSchedule, NoExecute)
      containers:
        - name: mods-taints
          image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mods-taints
  namespace: taint2
spec:
  selector:
    app: mods-taints
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP