apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-3-deployment
  namespace: taints
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mods-3
  template:
    metadata:
      labels:
        app: mods-3
    spec:
      containers:
      - name: mods-3
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
        ports:
        - containerPort: 8080
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: mods-3
  namespace: taints
spec:
  selector:
    app: mods-3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
