apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-selector-deployment
  namespace: nodeselector123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mods-selector
  template:
    metadata:
      labels:
        app: mods-selector
    spec:
      containers:
      - name: mods-selector
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
        ports:
        - containerPort: 8080
      nodeSelector:
        size: small
        
        

---
apiVersion: v1
kind: Service
metadata:
  name: mods-selector
  namespace: nodeselector123
spec:
  selector:
    app: mods-selector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
