apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  namespace: nodeaffinity1
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/my-app:latest
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disk
                operator: In
                values:
                - ssd
                - hdd

                
---
apiVersion: v1
kind: Service
metadata:
  name: mods-2
  namespace: nodeaffinity1
spec:
  selector:
    app: mods-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP