apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-deployment
  namespace: minh123
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mods
  template:
    metadata:
      labels:
        app: mods
    spec:
      containers:
      - name: mods
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
        ports:
        - containerPort: 8080
      tolerations:  # Đưa tolerations vào đây
        - key: "app"
          operator: "Equal"
          value: "frontend"
          effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: mods
  namespace: minh123
spec:
  selector:
    app: mods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
