apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-1-deployment
  namespace: minhtao2002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mods-1
  template:
    metadata:
      labels:
        app: mods-1
    spec:
      containers:
      - name: mods-1
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
        ports:
        - containerPort: 8080
      nodeSelector:
        ## This label is used to deploy the pod on matching nodes
        disk: ssd
        workload: production-1
---
apiVersion: v1
kind: Service
metadata:
  name: mods-1
  namespace: minhtao2002
spec:
  selector:
    app: mods-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
