apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-deployment
  namespace: minh2002
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mods
  template:
    metadata:
      labels:
        app: mods
    spec:
      tolerations:  # Đây là nơi để đưa tolerations
        - key: "app"         # Key của taint mà toleration áp dụng
          operator: "Equal"   # Phép toán so sánh (Equal, Exists, ...)
          value: "frontend"   # Giá trị của taint
          effect: "NoSchedule"  # Tác động của taint (NoSchedule, PreferNoSchedule, NoExecute)
      containers:
        - name: mods
          image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
          ports:
            - containerPort: 8080
