apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-1-deployment
  namespace: minhtao2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mods-2
  template:
    metadata:
      labels:
        app: mods-2
    spec:
      containers:
      - name: mods-2
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - production-1
                
---
apiVersion: v1
kind: Service
metadata:
  name: mods-2
  namespace: minhtao2
spec:
  selector:
    app: mods-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP