apiVersion: apps/v1
kind: Deployment
metadata:
  name: mods-deployment
  namespace: doan123
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mods-taints
  template:
    metadata:
      labels:
        app: mods-taints
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "frontend"
          effect: "NoSchedule"
      containers:
        - name: mods-taints
          image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/mods:latest
          ports:
            - containerPort: 8080
  nodeSelector:
    workload: production-1
    disk:ssd
---
apiVersion: v1
kind: Service
metadata:
  name: mods-taints
  namespace: doan123
spec:
  selector:
    app: mods-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
