CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  username VARCHAR(20) NOT NULL UNIQUE KEY,
  email VARCHAR(45) NOT NULL UNIQUE KEY,
  password VARCHAR(64) NOT NULL,
  roles VARCHAR(255) NOT NULL
);
