CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  date_created DATETIME NOT NULL,
  date_fulfilled DATETIME,
  total_price DECIMAL(10, 2) NOT NULL,
  status ENUM('ORDERED', 'DELIVERED', 'CANCELLED') NOT NULL
);

ALTER TABLE orders ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id);
